name: Build and Upload Artifact

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [x86, x64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ricochet_deobf.sln

      - name: Build solution (${{ matrix.platform }})
        run: |
          msbuild ricochet_deobf.sln `
            /p:Configuration=Release `
            /p:Platform=${{ matrix.platform }} `
            /p:OutDir="${{ github.workspace }}\build\${{ matrix.platform }}\"

      - name: Upload artifact (${{ matrix.platform }})
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: build/${{ matrix.platform }}/
